# Generated by Django 4.1 on 2022-08-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50, null=True)),
                ('name_ru', models.CharField(max_length=50, null=True)),
                ('text', models.CharField(max_length=1000)),
                ('text_en', models.CharField(max_length=1000, null=True)),
                ('text_ru', models.CharField(max_length=1000, null=True)),
            ],
            options={
                'verbose_name_plural': 'AboutUs',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=14)),
                ('location', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50, null=True)),
                ('name_ru', models.CharField(max_length=50, null=True)),
                ('text', models.CharField(max_length=1000)),
                ('text_en', models.CharField(max_length=1000, null=True)),
                ('text_ru', models.CharField(max_length=1000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Main',
            },
        ),
    ]
