# Generated by Django 4.0.6 on 2022-08-17 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ENGLISH', 'English'), ('RUSSIAN', 'Русский')], max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ENGLISH', 'English'), ('RUSSIAN', 'Русский')], max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=1000)),
            ],
        ),
    ]
