# Generated by Django 4.0.6 on 2022-08-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_app', '0002_aboutus_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('russian', 'Русский')], max_length=100),
        ),
        migrations.AlterField(
            model_name='main',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('russian', 'Русский')], max_length=100),
        ),
    ]
