# Generated by Django 4.0.6 on 2022-08-10 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='logo')),
                ('photo', models.ImageField(upload_to='company_photo')),
                ('information', models.TextField()),
                ('web_site', models.URLField()),
                ('language', models.CharField(choices=[('ENGLISH', 'English'), ('RUSSIAN', 'Русский')], max_length=20)),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='product_photo')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_photos', to='web_app.company')),
            ],
        ),
        migrations.CreateModel(
            name='ProductName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_name', to='web_app.company')),
            ],
        ),
    ]
