# Generated by Django 4.0.6 on 2022-08-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productname',
            name='company',
        ),
        migrations.AddField(
            model_name='productname',
            name='company',
            field=models.ManyToManyField(related_name='products_name', to='web_app.company'),
        ),
        migrations.RemoveField(
            model_name='productphoto',
            name='company',
        ),
        migrations.AddField(
            model_name='productphoto',
            name='company',
            field=models.ManyToManyField(related_name='products_photos', to='web_app.company'),
        ),
    ]
