# Generated by Django 4.0.6 on 2022-08-02 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_alter_company_options_alter_company_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='information',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='productname',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_name', to='web_app.company'),
        ),
    ]
