# Generated by Django 4.0.6 on 2022-08-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_remove_productname_company_productname_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='key_words',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='ProductName',
        ),
    ]
