# Generated by Django 4.0.6 on 2022-08-03 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_alter_company_information_alter_productname_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productname',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='web_app.company'),
        ),
    ]
