# Generated by Django 4.0.6 on 2022-08-04 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_alter_productname_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productname',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_name', to='web_app.company'),
        ),
        migrations.AlterField(
            model_name='productphoto',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_photos', to='web_app.company'),
        ),
    ]
